;;;; gcm.lisp — AES-GCM authenticated encryption (NIST SP 800-38D).

(in-package #:seal)

(defun gcm-shift-right (block)
  "Shift a 128-bit block right by one bit, in place."
  (let ((carry 0))
    (dotimes (i 16)
      (let ((new-carry (logand (aref block i) 1)))
        (setf (aref block i) (logior (ash (aref block i) -1) (ash carry 7)))
        (setf carry new-carry))))
  block)

(defun gcm-mul (x y)
  "Multiply two 16-byte blocks in GF(2^128). Returns a fresh 16-byte array."
  (let ((z (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0))
        (v (make-array 16 :element-type '(unsigned-byte 8))))
    (dotimes (i 16) (setf (aref v i) (aref y i)))
    (dotimes (i 16)
      (let ((xi (aref x i)))
        (dotimes (j 8)
          (when (logbitp (- 7 j) xi)
            (dotimes (k 16) (setf (aref z k) (logxor (aref z k) (aref v k)))))
          (let ((lsb (logand (aref v 15) 1)))
            (gcm-shift-right v)
            (when (= lsb 1) (setf (aref v 0) (logxor (aref v 0) #xe1)))))))
    z))

(defun gcm-ghash (h data)
  "GHASH over DATA (a multiple of 16 bytes) with hash subkey H."
  (let ((y (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0))
        (len (length data)))
    (do ((i 0 (+ i 16)))
        ((>= i len))
      (dotimes (j 16)
        (when (< (+ i j) len)
          (setf (aref y j) (logxor (aref y j) (aref data (+ i j))))))
      (let ((new-y (gcm-mul y h)))
        (dotimes (j 16) (setf (aref y j) (aref new-y j)))))
    y))

(defun gcm-inc32 (counter)
  "Increment the low 32-bit counter of a 16-byte counter block, in place."
  (let ((b (1+ (aref counter 15))))
    (if (< b 256)
        (setf (aref counter 15) b)
        (progn
          (setf (aref counter 15) 0
                b (1+ (aref counter 14)))
          (if (< b 256)
              (setf (aref counter 14) b)
              (progn
                (setf (aref counter 14) 0
                      b (1+ (aref counter 13)))
                (if (< b 256)
                    (setf (aref counter 13) b)
                    (progn
                      (setf (aref counter 13) 0
                            b (logand (1+ (aref counter 12)) #xff))
                      (setf (aref counter 12) b))))))))
  counter)

(defun %gcm-build-ghash-data (aad ciphertext)
  "Assemble AAD || pad || C || pad || len64(AAD) || len64(C)."
  (let* ((aad-len (length aad))
         (ct-len (length ciphertext))
         (aad-padded (* 16 (ceiling aad-len 16)))
         (ct-padded (* 16 (ceiling ct-len 16)))
         (data (make-array (+ aad-padded ct-padded 16)
                           :element-type '(unsigned-byte 8) :initial-element 0)))
    (dotimes (i aad-len) (setf (aref data i) (aref aad i)))
    (dotimes (i ct-len) (setf (aref data (+ aad-padded i)) (aref ciphertext i)))
    (let ((off (+ aad-padded ct-padded))
          (aad-bits (* aad-len 8))
          (ct-bits (* ct-len 8)))
      (dotimes (i 8)
        (setf (aref data (+ off i)) (logand (ash aad-bits (* -8 (- 7 i))) #xff)))
      (dotimes (i 8)
        (setf (aref data (+ off 8 i)) (logand (ash ct-bits (* -8 (- 7 i))) #xff))))
    data))

(defun %gcm-ctr (expanded-key rounds j0 input)
  "AES counter-mode XOR of INPUT, starting from counter J0+1."
  (let ((out (make-array (length input) :element-type '(unsigned-byte 8)))
        (counter (make-array 16 :element-type '(unsigned-byte 8)))
        (in-len (length input)))
    (dotimes (i 16) (setf (aref counter i) (aref j0 i)))
    (do ((i 0 (+ i 16)))
        ((>= i in-len))
      (gcm-inc32 counter)
      (let ((ks (aes-encrypt-block counter expanded-key rounds)))
        (dotimes (j 16)
          (when (< (+ i j) in-len)
            (setf (aref out (+ i j)) (logxor (aref input (+ i j)) (aref ks j)))))))
    out))

(defun aes-gcm-encrypt (key nonce plaintext aad)
  "AES-GCM encrypt. KEY 16/32 bytes, NONCE 12 bytes. Returns (ciphertext . tag)."
  (let* ((key-len (length key))
         (expanded-key (if (= key-len 16) (aes-expand-key-128 key) (aes-expand-key-256 key)))
         (rounds (if (= key-len 16) 10 14))
         (h (aes-encrypt-block (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)
                               expanded-key rounds))
         (j0 (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)))
    (dotimes (i 12) (setf (aref j0 i) (aref nonce i)))
    (setf (aref j0 15) 1)
    (let* ((ciphertext (%gcm-ctr expanded-key rounds j0 plaintext))
           (s (gcm-ghash h (%gcm-build-ghash-data aad ciphertext)))
           (j0-enc (aes-encrypt-block j0 expanded-key rounds)))
      (dotimes (i 16) (setf (aref s i) (logxor (aref s i) (aref j0-enc i))))
      (cons ciphertext s))))

(defun aes-gcm-decrypt (key nonce ciphertext aad tag)
  "AES-GCM decrypt. Returns plaintext, or NIL if the tag does not verify."
  (let* ((key-len (length key))
         (expanded-key (if (= key-len 16) (aes-expand-key-128 key) (aes-expand-key-256 key)))
         (rounds (if (= key-len 16) 10 14))
         (h (aes-encrypt-block (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)
                               expanded-key rounds))
         (j0 (make-array 16 :element-type '(unsigned-byte 8) :initial-element 0)))
    (dotimes (i 12) (setf (aref j0 i) (aref nonce i)))
    (setf (aref j0 15) 1)
    (let* ((s (gcm-ghash h (%gcm-build-ghash-data aad ciphertext)))
           (j0-enc (aes-encrypt-block j0 expanded-key rounds))
           (diff 0))
      (dotimes (i 16) (setf (aref s i) (logxor (aref s i) (aref j0-enc i))))
      ;; constant-time-ish tag comparison
      (dotimes (i 16) (setf diff (logior diff (logxor (aref s i) (aref tag i)))))
      (unless (zerop diff) (return-from aes-gcm-decrypt nil))
      (%gcm-ctr expanded-key rounds j0 ciphertext))))
